AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:

  DocManagementApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: doc-management-api
      StageName: prod
      Cors:
        AllowMethods: "'GET,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
        AllowOrigin: "'*'"

  ListDocumentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: list-documents
      Handler: getAllDocs.handler
      Runtime: nodejs18.x
      CodeUri: .
      Environment:
        Variables:
          BUCKET_NAME: my-ceportal-doc-storage
      Policies:
        - S3ReadPolicy:
            BucketName: my-ceportal-doc-storage
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref DocManagementApi
            Path: /documents
            Method: GET

  DeleteDocumentFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: delete-document
      Handler: deleteDoc.handler
      Runtime: nodejs18.x
      CodeUri: .
      Environment:
        Variables:
          BUCKET_NAME: my-ceportal-doc-storage
      Policies:
        - S3CrudPolicy:
            BucketName: my-ceportal-doc-storage
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref DocManagementApi
            Path: /documents/{id}
            Method: DELETE
